# generated by datamodel-codegen:
#   filename: openapi-v1.json (journey subset)

from __future__ import annotations

from typing import Any, Literal, Optional, TypedDict, Union

from typing_extensions import NotRequired


class Next(TypedDict):
    stageKey: str
    name: str
    source: Literal['operator', 'response', 'webhook', 'timer', 'fallback']
    scheduledFor: NotRequired[str]


class V1JourneyContactDto(TypedDict):
    email: NotRequired[str]
    phone: NotRequired[str]


class V1JourneyPendingMomentDto(TypedDict):
    key: str
    name: NotRequired[str]


class V1JourneyMomentProgressDto(TypedDict):
    key: str
    name: str
    status: Literal['pending', 'active', 'sent', 'responded', 'done', 'skipped']
    toolId: NotRequired[str]
    toolType: NotRequired[Literal['woku', 'csat', 'ces', 'nps', 'flow', 'form']]
    toolScope: NotRequired[Literal['shared', 'per_enrollment']]
    sentAt: NotRequired[str]
    respondedAt: NotRequired[str]
    activationSource: NotRequired[
        Literal['operator', 'response', 'webhook', 'timer', 'fallback']
    ]
    hookReceivedAt: NotRequired[str]


class ValidationErrorResponseDto(TypedDict):
    statusCode: float
    message: list[str]
    error: str


class V1JourneyTrackerDto(TypedDict):
    name: str
    value: str


class V1JourneyEnrollmentResponseDto(TypedDict):
    subjectKey: str
    journeyId: str


class StopJourneyParticipationDto(TypedDict):
    reason: NotRequired[str]


class V1JourneyConnectionDto(TypedDict):
    stageKey: str
    mode: Literal['woku_signature', 'url_token', 'sender_hmac']
    configured: bool
    url: str


class V1JourneyMomentUrlDto(TypedDict):
    token: str
    url: str


class SetSenderSecretDto(TypedDict):
    senderSecret: str


class V1PreviewJourneyMomentDto(TypedDict):
    payload: dict[str, Any]


class V1JourneyLocaleDto(TypedDict):
    es: NotRequired[str]
    en: NotRequired[str]


class V1JourneyPreviewFolderDto(TypedDict):
    secondaryKey: str
    name: str
    parentSecondaryKey: NotRequired[str]
    parentName: NotRequired[str]


class JourneyPlanMemberDto(TypedDict):
    userId: str
    role: Literal['admin', 'assignee']


class V1JourneyRoutingDto(TypedDict):
    ticketsReady: bool
    plansReady: bool
    ticketDestinationId: NotRequired[str]
    actionPlanGroupId: NotRequired[str]


class V1JourneyToolSpecDto(TypedDict):
    fileId: NotRequired[str]
    imageUrl: NotRequired[str]
    descriptionEn: NotRequired[str]
    subject: NotRequired[V1JourneyLocaleDto]
    audience: NotRequired[V1JourneyLocaleDto]


class V1JourneySendWindowDto(TypedDict):
    startHour: float
    endHour: float
    timeZone: str


class V1JourneyVerificationDto(TypedDict):
    mode: Literal['woku_signature', 'url_token', 'sender_hmac']
    header: NotRequired[str]
    encoding: NotRequired[Literal['hex', 'base64']]
    prefix: NotRequired[str]
    signedPayload: NotRequired[Literal['body', 'timestamp_dot_body']]
    timestampHeader: NotRequired[str]


class V1JourneyPayloadRuleDto(TypedDict):
    path: str
    equals: str


class V1JourneyClientFieldDto(TypedDict):
    key: str
    path: str


class V1JourneyTextValueDto(TypedDict):
    mode: Literal['literal', 'javascript']
    value: str


class V1JourneyDynamicLocaleDto(TypedDict):
    es: NotRequired[V1JourneyTextValueDto]
    en: NotRequired[V1JourneyTextValueDto]


class V1JourneyTrackerMappingDto(TypedDict):
    name: str
    path: str


class V1JourneySequenceDto(TypedDict):
    attemptOffsetsMs: list[float]
    deadlineMs: float
    cooldownAfterResponseMs: float
    sendWindow: NotRequired[V1JourneySendWindowDto]


class V1JourneyPresentationDto(TypedDict):
    imageUrl: NotRequired[str]
    copy_: NotRequired[V1JourneyLocaleDto]


class V1JourneyLegacyToolRefDto(TypedDict):
    type: Literal['csat', 'ces', 'woku', 'nps', 'flow', 'form']
    id: str


class V1JourneySecretResponseDto(TypedDict):
    webhookSecret: str


class V1EmitJourneyEventBodyDto(TypedDict):
    authHeader: NotRequired[str]
    event: str
    subjectKey: str
    contact: NotRequired[V1JourneyContactDto]
    trackers: NotRequired[list[V1JourneyTrackerDto]]
    metadata: NotRequired[dict[str, Any]]


class V1JourneyEventResponseDto(TypedDict):
    journeys: float


class JourneyEntryInfoDto(TypedDict):
    name: NotRequired[str]
    momentName: NotRequired[str]
    tool: Literal['woku', 'csat', 'ces', 'nps']
    requiresReference: bool


class PrepareJourneyEntryDto(TypedDict):
    requestId: str
    email: NotRequired[str]
    phone: NotRequired[str]
    reference: NotRequired[str]


class PreparedJourneyEntryDto(TypedDict):
    companyId: str
    tool: Literal['woku', 'csat', 'ces', 'nps']
    toolId: str
    token: str
    subjectKey: str


class V1JourneyParticipationDto(TypedDict):
    id: str
    subjectKey: str
    contact: V1JourneyContactDto
    lifecycle: Literal['pending', 'running', 'stopping', 'stopped', 'completed']
    definitionVersion: NotRequired[float]
    startedAt: NotRequired[str]
    startSource: NotRequired[Literal['operator', 'response', 'webhook']]
    stoppedAt: NotRequired[str]
    completedAt: NotRequired[str]
    stopRequestedAt: NotRequired[str]
    stoppedBy: NotRequired[str]
    stopReason: NotRequired[str]
    dispatchOutcomeUncertain: bool
    createdAt: NotRequired[str]
    pendingMoments: list[V1JourneyPendingMomentDto]
    moments: list[V1JourneyMomentProgressDto]
    next: Optional[Next]


class V1EnrollSubjectBodyDto(TypedDict):
    authHeader: NotRequired[str]
    subjectKey: str
    contact: V1JourneyContactDto
    trackers: NotRequired[list[V1JourneyTrackerDto]]
    metadata: NotRequired[dict[str, Any]]


class V1JourneyPreviewContentDto(TypedDict):
    title: str
    imageUrl: NotRequired[str]
    trackers: NotRequired[list[V1JourneyTrackerDto]]
    question: NotRequired[V1JourneyLocaleDto]
    folder: NotRequired[V1JourneyPreviewFolderDto]
    clientFields: dict[str, Union[str, float, bool]]


class JourneyRecipientsDto(TypedDict):
    ticketsEnabled: NotRequired[bool]
    plansEnabled: NotRequired[bool]
    ticketEmails: list[str]
    planMembers: list[JourneyPlanMemberDto]


class V1JourneyPayloadMapDto(TypedDict):
    subjectKey: NotRequired[str]
    email: NotRequired[str]
    phone: NotRequired[str]
    match: NotRequired[list[V1JourneyPayloadRuleDto]]
    clientFields: NotRequired[list[V1JourneyClientFieldDto]]


class V1JourneyWebhookContentDto(TypedDict):
    description: NotRequired[V1JourneyTextValueDto]
    descriptionEn: NotRequired[V1JourneyTextValueDto]
    folderSecondaryKey: NotRequired[V1JourneyTextValueDto]
    folderName: NotRequired[V1JourneyTextValueDto]
    parentFolderSecondaryKey: NotRequired[V1JourneyTextValueDto]
    parentFolderName: NotRequired[V1JourneyTextValueDto]
    subject: NotRequired[V1JourneyDynamicLocaleDto]
    audience: NotRequired[V1JourneyDynamicLocaleDto]
    imageUrlPath: NotRequired[str]
    trackers: NotRequired[list[V1JourneyTrackerMappingDto]]


class V1JourneyParticipationPageDto(TypedDict):
    items: list[V1JourneyParticipationDto]
    nextCursor: NotRequired[str]


class V1JourneyPreviewResponseDto(TypedDict):
    matches: bool
    subjectKey: str
    contact: V1JourneyContactDto
    preview: NotRequired[V1JourneyPreviewContentDto]


class V1JourneyTriggerDto(TypedDict):
    type: Literal['manual', 'event', 'webhook', 'afterStage']
    event: NotRequired[str]
    stage: NotRequired[str]
    anchor: NotRequired[Literal['sent', 'response', 'event']]
    delayMs: NotRequired[float]
    window: NotRequired[V1JourneySendWindowDto]
    verification: NotRequired[V1JourneyVerificationDto]
    payload: NotRequired[V1JourneyPayloadMapDto]


class V1JourneyWebhookDto(TypedDict):
    verification: NotRequired[V1JourneyVerificationDto]
    payload: NotRequired[V1JourneyPayloadMapDto]
    contentMode: NotRequired[Literal['manual', 'webhook']]
    schema_: NotRequired[dict[str, Any]]
    content: NotRequired[V1JourneyWebhookContentDto]


class V1JourneyMomentDto(TypedDict):
    key: str
    name: NotRequired[str]
    description: NotRequired[str]
    order: NotRequired[float]
    tool: Literal['woku', 'csat', 'ces', 'nps']
    toolScope: NotRequired[Literal['shared', 'per_enrollment']]
    toolSpec: NotRequired[V1JourneyToolSpecDto]
    enabled: bool
    trigger: V1JourneyTriggerDto
    webhook: NotRequired[V1JourneyWebhookDto]
    channel: Literal['email', 'whatsapp_first']
    sequence: V1JourneySequenceDto
    presentation: NotRequired[V1JourneyPresentationDto]
    fallbackAfterMs: NotRequired[float]
    fallbackFromStage: NotRequired[str]


class V1UpdateJourneyBodyDto(TypedDict):
    authHeader: NotRequired[str]
    authoringVersion: NotRequired[Literal[1, 2]]
    startMode: NotRequired[Literal['operator', 'response', 'webhook']]
    recipients: NotRequired[JourneyRecipientsDto]
    name: NotRequired[str]
    enabled: NotRequired[bool]
    moments: NotRequired[list[V1JourneyMomentDto]]


class V1JourneyMomentReadDto(TypedDict):
    key: str
    name: NotRequired[str]
    description: NotRequired[str]
    order: NotRequired[float]
    tool: Literal['woku', 'csat', 'ces', 'nps']
    toolScope: NotRequired[Literal['shared', 'per_enrollment']]
    toolSpec: NotRequired[V1JourneyToolSpecDto]
    enabled: bool
    trigger: V1JourneyTriggerDto
    webhook: NotRequired[V1JourneyWebhookDto]
    channel: Literal['email', 'whatsapp_first']
    sequence: V1JourneySequenceDto
    presentation: NotRequired[V1JourneyPresentationDto]
    fallbackAfterMs: NotRequired[float]
    fallbackFromStage: NotRequired[str]
    toolRef: NotRequired[V1JourneyLegacyToolRefDto]


class V1CreateJourneyBodyDto(TypedDict):
    authHeader: NotRequired[str]
    authoringVersion: NotRequired[Literal[1, 2]]
    startMode: NotRequired[Literal['operator', 'response', 'webhook']]
    recipients: NotRequired[JourneyRecipientsDto]
    name: str
    enabled: NotRequired[bool]
    moments: NotRequired[list[V1JourneyMomentDto]]


class V1CreatedJourneyResponseDto(TypedDict):
    id: str
    key: NotRequired[str]
    name: NotRequired[str]
    enabled: bool
    version: float
    authoringVersion: NotRequired[Literal[1, 2]]
    startMode: NotRequired[Literal['operator', 'response', 'webhook']]
    recipients: NotRequired[JourneyRecipientsDto]
    routing: NotRequired[V1JourneyRoutingDto]
    moments: list[V1JourneyMomentReadDto]
    createdAt: NotRequired[str]
    updatedAt: NotRequired[str]
    webhookSecret: str


class V1JourneyResponseDto(TypedDict):
    id: str
    key: NotRequired[str]
    name: NotRequired[str]
    enabled: bool
    version: float
    authoringVersion: NotRequired[Literal[1, 2]]
    startMode: NotRequired[Literal['operator', 'response', 'webhook']]
    recipients: NotRequired[JourneyRecipientsDto]
    routing: NotRequired[V1JourneyRoutingDto]
    moments: list[V1JourneyMomentReadDto]
    createdAt: NotRequired[str]
    updatedAt: NotRequired[str]
