# generated by datamodel-codegen:
#   filename:  openapi-v1.json

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Annotated, Any, Optional, Union
from uuid import UUID

from pydantic import BaseModel, Field


class ValidationErrorResponseDto(BaseModel):
    statusCode: Annotated[float, Field(examples=[400])]
    """
    HTTP status code
    """
    message: Annotated[
        list[str],
        Field(
            examples=[
                [
                    'email must be a valid email',
                    'password must be at least 8 characters',
                ]
            ]
        ),
    ]
    """
    Array of validation error messages
    """
    error: Annotated[str, Field(examples=['Bad Request'])]
    """
    Error type
    """


class CreateWokuApiDto(BaseModel):
    description: str
    """
    The subject evaluated by this Woku
    """
    fileUrl: str
    """
    Public image or MP4 URL
    """
    folderSecondaryKey: Optional[str] = None
    parentFolderSecondaryKey: Optional[str] = None
    clientEmail: Optional[str] = None
    clientPhone: Optional[float] = None


class CreateWokuFormDataApiDto(BaseModel):
    description: str
    """
    The subject evaluated by this Woku
    """
    folderSecondaryKey: Optional[str] = None
    parentFolderSecondaryKey: Optional[str] = None
    clientEmail: Optional[str] = None
    clientPhone: Optional[str] = None


class CreateExternalTrackerDefinitionDTO(BaseModel):
    name: Annotated[str, Field(examples=['trr'], max_length=60, min_length=1)]
    """
    Tracker name. Identifies the tracker within the company catalog. Unique per company.
    """
    system: Annotated[str, Field(examples=['crm interno'], max_length=80)]
    """
    External system this tracker maps to.
    """
    description: Annotated[
        Optional[str],
        Field(examples=['transaction id of a lease or sale'], max_length=500),
    ] = None
    """
    Human-readable description of the tracker.
    """


class AssignWokuExternalTrackerByNameDTO(BaseModel):
    name: Annotated[str, Field(examples=['trr'], max_length=60)]
    """
    Name of the company-level external tracker definition this value belongs to.
    """
    value: Annotated[str, Field(examples=['dasdj123kdak32'], max_length=500)]
    """
    External identifier value (always stored as string).
    """


class ExternalTrackerFilterDTO(BaseModel):
    name: Annotated[str, Field(examples=['trr'], max_length=60)]
    """
    Tracker name (resolved to its definition server-side).
    """
    value: Annotated[str, Field(examples=['ABC'], max_length=500)]
    """
    Value to match (partial, case-insensitive).
    """


class EntityType(Enum):
    """
    VoC entity type to search.
    """

    nps = 'nps'
    csat = 'csat'
    ces = 'ces'
    form = 'form'
    flow = 'flow'


class SearchEntitiesByTrackersDTO(BaseModel):
    entityType: Annotated[EntityType, Field(examples=['nps'])]
    """
    VoC entity type to search.
    """
    filters: Annotated[
        list[ExternalTrackerFilterDTO], Field(max_length=50, min_length=1)
    ]
    """
    Tracker filters combined with AND. Each entity must match every filter to be returned.
    """


class UpdateExternalTrackerDefinitionDTO(BaseModel):
    name: Annotated[Optional[str], Field(max_length=60, min_length=1)] = None
    """
    New name (must remain unique within the company).
    """
    system: Annotated[Optional[str], Field(max_length=80)] = None
    """
    New external system identifier.
    """
    description: Annotated[Optional[str], Field(max_length=500)] = None
    """
    New description.
    """


class AssignExternalTrackerByNameDTO(BaseModel):
    name: Annotated[str, Field(examples=['trr'], max_length=60)]
    """
    Name of the company-level external tracker definition this value belongs to.
    """
    value: Annotated[str, Field(examples=['dasdj123kdak32'], max_length=500)]
    """
    External identifier value (always stored as string).
    """


class RelationToPrevious(Enum):
    AND = 'AND'
    OR = 'OR'


class Operator(Enum):
    equals = 'equals'
    any = 'any'


class TicketRoutingConditionDto(BaseModel):
    relationToPrevious: Optional[RelationToPrevious] = None
    trackerId: str
    """
    CompanyExternalTracker id.
    """
    operator: Optional[Operator] = 'equals'
    value: Optional[str] = None
    """
    The value the tracker must equal. Required unless operator is "any".
    """


class TicketDestinationTemplateDto(BaseModel):
    preset: Annotated[str, Field(examples=['custom'])]
    body: Optional[str] = None
    """
    Custom JSON body with {{path}} placeholders.
    """


class Kind(Enum):
    zendesk = 'zendesk'
    custom = 'custom'
    email = 'email'


class V1CreateTicketDestinationDto(BaseModel):
    name: Annotated[str, Field(examples=['Zendesk Soporte Chile'], max_length=120)]
    config: dict[str, Any]
    """
    Non-secret provider config (validated per kind).
    """
    credentials: dict[str, str]
    """
    Provider credentials (write-only, encrypted).
    """
    aiContext: Annotated[Optional[str], Field(max_length=2000)] = None
    """
    Per-destination AI triage context.
    """
    routingConditions: Optional[list[TicketRoutingConditionDto]] = None
    template: Optional[TicketDestinationTemplateDto] = None
    kind: Kind


class V1UpdateTicketDestinationDto(BaseModel):
    name: Annotated[Optional[str], Field(max_length=120)] = None
    config: Optional[dict[str, Any]] = None
    credentials: Optional[dict[str, str]] = None
    """
    Present = credential rotation.
    """
    aiContext: Annotated[Optional[str], Field(max_length=2000)] = None
    """
    Per-destination AI triage context.
    """
    routingConditions: Optional[list[TicketRoutingConditionDto]] = None
    template: Optional[TicketDestinationTemplateDto] = None
    enabled: Optional[bool] = None
    kind: Optional[Kind] = None


class TestTicketDestinationBodyDTO(BaseModel):
    confirm: bool
    """
    Must be true. The test sends a real request to the destination (custom webhooks receive a test payload; other kinds run a read-only auth probe).
    """


class ActionPlanGroupConditionDto(BaseModel):
    relationToPrevious: Optional[RelationToPrevious] = None
    trackerId: str
    """
    CompanyExternalTracker id.
    """
    operator: Optional[Operator] = 'equals'
    value: Optional[str] = None
    """
    The value the tracker must equal. Required unless operator is "any".
    """


class Role(Enum):
    admin = 'admin'
    assignee = 'assignee'


class ActionPlanGroupMemberDto(BaseModel):
    userId: str
    """
    Company member user id.
    """
    role: Role


class CreateActionPlanGroupDto(BaseModel):
    notificationEmails: Optional[list[str]] = None
    """
    Additional email recipients; grants no membership.
    """
    name: Annotated[str, Field(examples=['Atención en tienda'], max_length=120)]
    description: Annotated[Optional[str], Field(max_length=500)] = None
    conditions: list[ActionPlanGroupConditionDto]
    """
    Tracker conditions; at least one row is required.
    """
    members: list[ActionPlanGroupMemberDto]
    """
    Group team; at least one admin (assignees optional).
    """
    threshold: Annotated[Optional[float], Field(ge=1.0)] = 300
    """
    New improvement comments that trigger a plan draft (default 300).
    """


class UpdateActionPlanGroupDto(BaseModel):
    notificationEmails: Optional[list[str]] = None
    """
    Additional email recipients; grants no membership.
    """
    name: Annotated[Optional[str], Field(max_length=120)] = None
    description: Annotated[Optional[str], Field(max_length=500)] = None
    """
    Empty string clears.
    """
    conditions: Optional[list[ActionPlanGroupConditionDto]] = None
    members: Optional[list[ActionPlanGroupMemberDto]] = None
    threshold: Annotated[Optional[float], Field(ge=1.0)] = None


class SetActionPlanGroupEnabledDto(BaseModel):
    enabled: bool


class PostPlanReplyBodyDTO(BaseModel):
    text: Annotated[str, Field(max_length=4000, min_length=1)]
    """
    Message to send to the plan AI agent.
    """
    confirm: bool
    """
    Must be true. Each reply triggers a paid AI turn; the reply is composed asynchronously and delivered over the plan channel.
    """


class Provider(Enum):
    """
    Only `internal` (manage the plan inside woku) is available.
    """

    internal = 'internal'


class V1SendActionPlanDto(BaseModel):
    provider: Provider
    """
    Only `internal` (manage the plan inside woku) is available.
    """
    resourceLabel: Annotated[Optional[str], Field(max_length=300)] = None
    """
    Optional human-readable label for the destination.
    """


class CreateActionPlanTaskDto(BaseModel):
    text: Annotated[str, Field(max_length=160)]
    """
    Task text.
    """


class ReorderActionPlanTasksDto(BaseModel):
    orderedTaskIds: list[str]
    """
    All task ids in the desired order.
    """


class Status(Enum):
    todo = 'todo'
    in_progress = 'in_progress'
    done = 'done'


class UpdateActionPlanTaskDto(BaseModel):
    text: Annotated[Optional[str], Field(max_length=160)] = None
    """
    New task text.
    """
    status: Optional[Status] = None
    assigneeId: Optional[str] = None
    """
    Group member responsible; null/"" clears the assignee.
    """


class Locale(Enum):
    es = 'es'
    en = 'en'


class V1WokuLocalizedContentDTO(BaseModel):
    locale: Annotated[Locale, Field(examples=['en'])]
    description: Annotated[str, Field(max_length=140, min_length=3)]


class DefaultLocale(Enum):
    es = 'es'
    en = 'en'


class UpdateWokuBodyDTO(BaseModel):
    description: Annotated[Optional[str], Field(max_length=140, min_length=3)] = None
    """
    Woku description/title.
    """
    availableLocales: Annotated[Optional[list[str]], Field(examples=[['es', 'en']])] = (
        None
    )
    """
    Locales the survey is available in (subset of es/en).
    """
    defaultLocale: Optional[DefaultLocale] = None
    localizedContent: Optional[list[V1WokuLocalizedContentDTO]] = None


class UpdateWokuSettingsBodyDTO(BaseModel):
    closed: Optional[bool] = None
    """
    Whether the woku is closed to new reviews.
    """
    reviewsDisabled: Optional[bool] = None
    """
    Whether new reviews are disabled.
    """
    anonymousDisabled: Optional[bool] = None
    """
    Whether anonymous reviews are disabled.
    """
    onlyOneReviewPerClient: Optional[bool] = None
    """
    Whether each client may leave only one review.
    """


class MoveWokuBodyDTO(BaseModel):
    folderId: str
    """
    Target folder id, or null to move the woku to the root.
    """


class V1CreateTextnoteBodyDto(BaseModel):
    dispatchToken: Annotated[Optional[str], Field(max_length=64)] = None
    """
    Opaque invitation or prepared journey-entry response token. Consumed after saving feedback; never stored on the review.
    """
    qualification: Annotated[float, Field(examples=[5])]
    """
    Star rating (1-5)
    """
    description: str
    """
    Text content of the review (max 3000 chars)
    """
    clientEmail: Optional[str] = None
    """
    Reviewer email
    """
    clientPhone: Optional[str] = None
    """
    Reviewer phone
    """
    anonymous: Optional[bool] = None
    """
    Whether the review is anonymous
    """
    responseChannel: Annotated[
        Optional[str], Field(examples=['my-crm'], max_length=48)
    ] = None
    """
    Inbound response channel. Defaults to 'api'; a value provided here REPLACES 'api' (user-defined channel).
    """


class Qualification(Enum):
    """
    Star rating (1-5)
    """

    field_1 = '1'
    field_2 = '2'
    field_3 = '3'
    field_4 = '4'
    field_5 = '5'


class Language(Enum):
    """
    Spoken language used to improve audio transcription
    """

    es = 'es'
    en = 'en'


class Anonymous(Enum):
    """
    Whether the review is anonymous
    """

    true = 'true'
    false = 'false'


class V1CreateVoicemailBodyDto(BaseModel):
    dispatchToken: Annotated[Optional[str], Field(max_length=64)] = None
    """
    Opaque invitation or prepared journey-entry response token. Consumed after saving feedback; never stored on the review.
    """
    file: bytes
    """
    Audio file for the voicemail
    """
    qualification: Annotated[Qualification, Field(examples=['5'])]
    """
    Star rating (1-5)
    """
    language: Annotated[Language, Field(examples=['es'])]
    """
    Spoken language used to improve audio transcription
    """
    clientEmail: Optional[str] = None
    """
    Reviewer email
    """
    clientPhone: Optional[str] = None
    """
    Reviewer phone
    """
    anonymous: Optional[Anonymous] = None
    """
    Whether the review is anonymous
    """
    responseChannel: Annotated[
        Optional[str], Field(examples=['my-crm'], max_length=48)
    ] = None
    """
    Inbound response channel. Defaults to 'api'; a value provided here REPLACES 'api' (user-defined channel).
    """


class V1ShareWokuBodyDto(BaseModel):
    clientEmail: Optional[str] = None
    """
    Single email address
    """
    clientEmails: Optional[list[str]] = None
    """
    Array of email addresses
    """


class Type(Enum):
    image = 'image'
    video = 'video'


class WokuMediaUploadResultDto(BaseModel):
    fileId: str
    filename: str
    type: Type


class V1ApiKeyResultDto(BaseModel):
    apiKey: str
    """
    The new company secret API key. The previous key is now invalid; store this value, it is not retrievable again.
    """


class V1RevokeApiKeyResultDto(BaseModel):
    revoked: Annotated[bool, Field(examples=[True])]
    """
    Always true once the key has been revoked.
    """


class V1CreateNpsBodyDto(BaseModel):
    score: Annotated[float, Field(examples=[9], ge=0.0, le=10.0)]
    """
    NPS score 0-10 (0-6 detractor, 7-8 passive, 9-10 promoter)
    """
    npsToolId: Optional[str] = None
    """
    Optional NPS tool id. With it the capture is tool-specific; without it, company-level.
    """
    clientEmail: Optional[str] = None
    """
    Respondent email. Omit for an anonymous capture.
    """
    clientPhone: Optional[str] = None
    """
    Respondent phone when email is not supplied.
    """
    anonymous: Optional[bool] = None
    """
    Whether the submission is anonymous (no client email stored).
    """
    responseChannel: Annotated[
        Optional[str], Field(examples=['my-crm'], max_length=48)
    ] = None
    """
    Inbound response channel. Defaults to 'api'; a value provided here REPLACES 'api' (user-defined channel). Stored on the NPS.
    """
    dispatchToken: Annotated[
        Optional[str], Field(examples=['a1b2c3d4-...'], max_length=64)
    ] = None
    """
    Opaque invitation dispatch token echoed from the link (?dtoken=). Consumed to mark the outbound invitation responded; never persisted.
    """


class V1CreateNpsTextnoteBodyDto(BaseModel):
    description: Annotated[
        str, Field(examples=['El producto cumple mis expectativas.'], max_length=3000)
    ]
    """
    Text feedback content
    """


class V1CreateCsatBodyDto(BaseModel):
    score: Annotated[float, Field(examples=[4], ge=1.0, le=5.0)]
    """
    CSAT satisfaction score 1-5
    """
    csatToolId: str
    """
    CSAT tool id (always required: CSAT tools are always custom)
    """
    clientEmail: Optional[str] = None
    """
    Respondent email. Omit for an anonymous capture.
    """
    anonymous: Optional[bool] = None
    """
    Whether the submission is anonymous (no client email stored).
    """
    responseChannel: Annotated[
        Optional[str], Field(examples=['my-crm'], max_length=48)
    ] = None
    """
    Inbound response channel. Defaults to 'api'; a value provided here REPLACES 'api' (user-defined channel). Stored on the response.
    """
    dispatchToken: Annotated[Optional[str], Field(max_length=64)] = None
    """
    Opaque invitation dispatch token echoed from the link (?dtoken=). Consumed to mark the outbound invitation responded; never persisted.
    """


class V1CreateCsatTextnoteBodyDto(BaseModel):
    description: Annotated[
        str, Field(examples=['El proceso fue muy facil.'], max_length=3000)
    ]
    """
    Text feedback content
    """


class V1CreateCesBodyDto(BaseModel):
    score: Annotated[float, Field(examples=[4], ge=1.0, le=5.0)]
    """
    CES effort score 1-5
    """
    cesToolId: str
    """
    CES tool id (always required: CES tools are always custom)
    """
    clientEmail: Optional[str] = None
    """
    Respondent email. Omit for an anonymous capture.
    """
    anonymous: Optional[bool] = None
    """
    Whether the submission is anonymous (no client email stored).
    """
    responseChannel: Annotated[
        Optional[str], Field(examples=['my-crm'], max_length=48)
    ] = None
    """
    Inbound response channel. Defaults to 'api'; a value provided here REPLACES 'api' (user-defined channel). Stored on the response.
    """
    dispatchToken: Annotated[Optional[str], Field(max_length=64)] = None
    """
    Opaque invitation dispatch token echoed from the link (?dtoken=). Consumed to mark the outbound invitation responded; never persisted.
    """


class V1CreateCesTextnoteBodyDto(BaseModel):
    description: Annotated[
        str, Field(examples=['Resolver fue muy facil.'], max_length=3000)
    ]
    """
    Text feedback content
    """


class V1CaptureAudioDto(BaseModel):
    uri: Optional[str] = None
    """
    Device-local URI of the recorded audio
    """
    mimeType: Optional[str] = None
    """
    Audio MIME type, e.g. audio/m4a
    """
    durationMs: Optional[float] = None
    """
    Duration in milliseconds
    """


class V1CaptureRespondentDto(BaseModel):
    email: Optional[str] = None
    """
    Respondent email
    """
    phone: Optional[str] = None
    """
    Respondent phone
    """
    externalId: Optional[str] = None
    """
    Host-app external id (e.g. CRM id)
    """


class Kind2(Enum):
    woku = 'woku'
    nps = 'nps'
    csat = 'csat'
    ces = 'ces'


class Language1(Enum):
    """
    Spoken language. Required when the capture includes an audio file.
    """

    es = 'es'
    en = 'en'


class V1CaptureBodyDto(BaseModel):
    dispatchToken: Annotated[Optional[str], Field(max_length=64)] = None
    """
    Opaque invitation or prepared journey-entry response token. Consumed after saving feedback; never stored on the review.
    """
    id: Optional[str] = None
    """
    Client-generated idempotency id
    """
    kind: Annotated[Kind2, Field(examples=['woku'])]
    language: Optional[Language1] = None
    """
    Spoken language. Required when the capture includes an audio file.
    """
    targetId: Optional[str] = None
    """
    Target id: the wokuId for a woku capture, the (optional) npsToolId for an NPS capture, or the (required) csatToolId/cesToolId for a CSAT/CES capture (those tools are always custom).
    """
    rating: Annotated[Optional[float], Field(examples=[5])] = None
    """
    Woku star rating 1-5
    """
    score: Annotated[Optional[float], Field(examples=[9])] = None
    """
    NPS score 0-10
    """
    comment: Annotated[Optional[str], Field(max_length=3000)] = None
    """
    Free-text comment
    """
    audio: Optional[V1CaptureAudioDto] = None
    respondent: Optional[V1CaptureRespondentDto] = None


class Status1(Enum):
    accepted = 'accepted'


class V1CaptureResultDto(BaseModel):
    id: Optional[str] = None
    """
    Client submission id, echoed without replacing the server id.
    """
    kind: Kind2
    remoteId: Optional[str] = None
    """
    Server id of the created feedback resource.
    """
    status: Status1


class Channel(Enum):
    """
    Delivery channel for the invitations
    """

    email = 'email'
    whatsapp = 'whatsapp'


class Language2(Enum):
    """
    Language of the invitation template
    """

    es = 'es'
    en = 'en'


class V1CreateNpsInvitationsBodyDto(BaseModel):
    channel: Annotated[Channel, Field(examples=['whatsapp'])]
    """
    Delivery channel for the invitations
    """
    recipients: Annotated[list[str], Field(examples=[['56912345678']], max_length=100)]
    """
    Recipients: email addresses for the email channel, phone numbers (digits, country code included, e.g. 56912345678) for whatsapp
    """
    language: Annotated[Optional[Language2], Field(examples=['es'])] = None
    """
    Language of the invitation template
    """
    npsToolId: Optional[str] = None
    """
    NPS tool to survey for. Omit to send the company-level NPS survey.
    """


class Reason(Enum):
    """
    Why the invitation was not dispatched
    """

    invalid_recipient = 'invalid_recipient'
    quarantined = 'quarantined'
    insufficient_credits_or_blocked = 'insufficient_credits_or_blocked'
    send_failed = 'send_failed'


class V1RejectedInvitationDto(BaseModel):
    recipient: str
    """
    Recipient as received in the request
    """
    reason: Reason
    """
    Why the invitation was not dispatched
    """


class Channel1(Enum):
    email = 'email'
    whatsapp = 'whatsapp'


class V1InvitationsResultDto(BaseModel):
    channel: Channel1
    accepted: list[str]
    """
    Recipients whose invitation was dispatched (or queued)
    """
    rejected: list[V1RejectedInvitationDto]
    """
    Recipients whose invitation was not dispatched, with reason
    """


class Channel2(Enum):
    """
    Delivery channel for the invitations
    """

    email = 'email'
    whatsapp = 'whatsapp'


class V1CreateCsatInvitationsBodyDto(BaseModel):
    channel: Annotated[Channel2, Field(examples=['whatsapp'])]
    """
    Delivery channel for the invitations
    """
    recipients: Annotated[list[str], Field(examples=[['56912345678']], max_length=100)]
    """
    Recipients: email addresses for the email channel, phone numbers (digits, country code included, e.g. 56912345678) for whatsapp
    """
    language: Annotated[Optional[Language2], Field(examples=['es'])] = None
    """
    Language of the invitation template
    """
    csatToolId: str
    """
    CSAT tool to survey for (always required: always custom).
    """


class V1CreateCesInvitationsBodyDto(BaseModel):
    channel: Annotated[Channel2, Field(examples=['whatsapp'])]
    """
    Delivery channel for the invitations
    """
    recipients: Annotated[list[str], Field(examples=[['56912345678']], max_length=100)]
    """
    Recipients: email addresses for the email channel, phone numbers (digits, country code included, e.g. 56912345678) for whatsapp
    """
    language: Annotated[Optional[Language2], Field(examples=['es'])] = None
    """
    Language of the invitation template
    """
    cesToolId: str
    """
    CES tool to survey for (always required: always custom).
    """


class V1CreateInvitationsBodyDto(BaseModel):
    channel: Annotated[Channel2, Field(examples=['whatsapp'])]
    """
    Delivery channel for the invitations
    """
    recipients: Annotated[list[str], Field(examples=[['56912345678']], max_length=100)]
    """
    Recipients: email addresses for the email channel, phone numbers (digits, country code included, e.g. 56912345678) for whatsapp
    """
    language: Annotated[Optional[Language2], Field(examples=['es'])] = None
    """
    Language of the invitation template
    """


class V1CreateFormResponseBodyDto(BaseModel):
    anonymous: Annotated[bool, Field(examples=[False])]
    """
    Whether this response is anonymous
    """
    email: Annotated[Optional[str], Field(examples=['respondent@example.com'])] = None
    """
    Email of the respondent (required when the form identifies clients by email and the response is not anonymous)
    """
    phone: Annotated[Optional[str], Field(examples=['+56912345678'])] = None
    """
    Phone of the respondent (required when the form identifies clients by phone and the response is not anonymous)
    """
    answers: Annotated[
        dict[str, Any],
        Field(examples=[{'field-uuid-1': 'John Doe', 'field-uuid-2': 5}]),
    ]
    """
    Answers keyed by field id
    """
    responseChannel: Annotated[
        Optional[str], Field(examples=['my-crm'], max_length=48)
    ] = None
    """
    Inbound response channel. Defaults to 'api'; a value provided here REPLACES 'api' (user-defined channel). Stored on the response.
    """
    dispatchToken: Annotated[
        Optional[str], Field(examples=['a1b2c3d4-...'], max_length=64)
    ] = None
    """
    Opaque invitation dispatch token echoed from the link (?dtoken=). Consumed to mark the outbound invitation responded; never persisted.
    """


class NpsToolLocalizedContentBodyDTO(BaseModel):
    locale: Annotated[Locale, Field(examples=['en'])]
    npsMessage: Annotated[
        str, Field(examples=['our company'], max_length=140, min_length=3)
    ]
    """
    Recommended company/product/service fragment for this locale (e.g. "our company"), NOT the full question.
    """
    audienceType: Annotated[
        Optional[str], Field(examples=['a friend or colleague'], max_length=140)
    ] = None
    """
    Audience fragment for this locale, NOT the full question.
    """


class DefaultLocale1(Enum):
    """
    Default locale used when none is requested.
    """

    es = 'es'
    en = 'en'


class CreateNpsToolBodyDTO(BaseModel):
    name: Annotated[str, Field(examples=['Post-Purchase Survey'], max_length=140)]
    """
    Tool name for identification.
    """
    npsMessage: Annotated[
        str, Field(examples=['our company'], max_length=140, min_length=3)
    ]
    """
    Only the company, product or service recommended (e.g. "our company"), NOT the full question. The public question is composed as "On a scale of 0 to 10, how likely are you to recommend {npsMessage} to {audienceType}?".
    """
    audienceType: Annotated[
        Optional[str], Field(examples=['a friend or colleague'], max_length=140)
    ] = None
    """
    Only who the survey targets (e.g. "a friend or colleague"), NOT the full question.
    """
    availableLocales: Annotated[Optional[list[str]], Field(examples=[['es', 'en']])] = (
        None
    )
    """
    Locales the tool is available in (subset of es/en).
    """
    defaultLocale: Annotated[Optional[DefaultLocale1], Field(examples=['es'])] = None
    """
    Default locale used when none is requested.
    """
    localizedContent: Optional[list[NpsToolLocalizedContentBodyDTO]] = None


class DefaultLocale2(Enum):
    es = 'es'
    en = 'en'


class UpdateNpsToolBodyDTO(BaseModel):
    name: Annotated[Optional[str], Field(max_length=140)] = None
    npsMessage: Annotated[
        Optional[str], Field(examples=['our company'], max_length=140, min_length=3)
    ] = None
    """
    Recommended company/product/service fragment (e.g. "our company"), NOT the full question.
    """
    audienceType: Annotated[
        Optional[str], Field(examples=['a friend or colleague'], max_length=140)
    ] = None
    """
    Audience fragment (e.g. "partners"), NOT the full question.
    """
    availableLocales: Annotated[Optional[list[str]], Field(examples=[['es', 'en']])] = (
        None
    )
    defaultLocale: Optional[DefaultLocale2] = None
    localizedContent: Optional[list[NpsToolLocalizedContentBodyDTO]] = None


class CsatToolLocalizedContentBodyDTO(BaseModel):
    locale: Annotated[Locale, Field(examples=['en'])]
    question: Annotated[
        str,
        Field(
            examples=['How satisfied are you with your purchase?'],
            max_length=140,
            min_length=3,
        ),
    ]
    """
    Translated CSAT question for this locale.
    """
    subject: Annotated[
        Optional[str], Field(examples=['your purchase'], max_length=140)
    ] = None
    """
    Translated subject for this locale.
    """


class DefaultLocale3(Enum):
    """
    Default locale used when none is requested.
    """

    es = 'es'
    en = 'en'


class CreateCsatToolBodyDTO(BaseModel):
    name: Annotated[str, Field(examples=['Post-Purchase CSAT'], max_length=140)]
    """
    Tool name for identification.
    """
    question: Annotated[
        str,
        Field(
            examples=['How satisfied are you with your purchase?'],
            max_length=140,
            min_length=3,
        ),
    ]
    """
    Public CSAT question shown to respondents.
    """
    subject: Annotated[
        Optional[str], Field(examples=['your purchase'], max_length=140)
    ] = None
    """
    Static variable filling 'how satisfied are you with [subject]?'.
    """
    availableLocales: Annotated[Optional[list[str]], Field(examples=[['es', 'en']])] = (
        None
    )
    """
    Locales the tool is available in (subset of es/en).
    """
    defaultLocale: Annotated[Optional[DefaultLocale3], Field(examples=['es'])] = None
    """
    Default locale used when none is requested.
    """
    localizedContent: Optional[list[CsatToolLocalizedContentBodyDTO]] = None


class DefaultLocale4(Enum):
    es = 'es'
    en = 'en'


class UpdateCsatToolBodyDTO(BaseModel):
    name: Annotated[Optional[str], Field(max_length=140)] = None
    question: Annotated[Optional[str], Field(max_length=140, min_length=3)] = None
    subject: Annotated[Optional[str], Field(max_length=140)] = None
    availableLocales: Annotated[Optional[list[str]], Field(examples=[['es', 'en']])] = (
        None
    )
    defaultLocale: Optional[DefaultLocale4] = None
    localizedContent: Optional[list[CsatToolLocalizedContentBodyDTO]] = None


class CesToolLocalizedContentBodyDTO(BaseModel):
    locale: Annotated[Locale, Field(examples=['en'])]
    question: Annotated[
        str,
        Field(
            examples=['How easy was it to complete your purchase?'],
            max_length=140,
            min_length=3,
        ),
    ]
    """
    Translated CES question for this locale.
    """
    action: Annotated[
        Optional[str], Field(examples=['complete your purchase'], max_length=140)
    ] = None
    """
    Translated action for this locale.
    """


class DefaultLocale5(Enum):
    """
    Default locale used when none is requested.
    """

    es = 'es'
    en = 'en'


class CreateCesToolBodyDTO(BaseModel):
    name: Annotated[str, Field(examples=['Post-Purchase Effort'], max_length=140)]
    """
    Tool name for identification.
    """
    question: Annotated[
        str,
        Field(
            examples=['How easy was it to complete your purchase?'],
            max_length=140,
            min_length=3,
        ),
    ]
    """
    Public effort question shown to respondents.
    """
    action: Annotated[
        Optional[str], Field(examples=['complete your purchase'], max_length=140)
    ] = None
    """
    Static variable filling 'how easy was it to [action]?'.
    """
    availableLocales: Annotated[Optional[list[str]], Field(examples=[['es', 'en']])] = (
        None
    )
    """
    Locales the tool is available in (subset of es/en).
    """
    defaultLocale: Annotated[Optional[DefaultLocale5], Field(examples=['es'])] = None
    """
    Default locale used when none is requested.
    """
    localizedContent: Optional[list[CesToolLocalizedContentBodyDTO]] = None


class DefaultLocale6(Enum):
    es = 'es'
    en = 'en'


class UpdateCesToolBodyDTO(BaseModel):
    name: Annotated[Optional[str], Field(max_length=140)] = None
    question: Annotated[Optional[str], Field(max_length=140, min_length=3)] = None
    action: Annotated[Optional[str], Field(max_length=140)] = None
    availableLocales: Annotated[Optional[list[str]], Field(examples=[['es', 'en']])] = (
        None
    )
    defaultLocale: Optional[DefaultLocale6] = None
    localizedContent: Optional[list[CesToolLocalizedContentBodyDTO]] = None


class Severity(Enum):
    high = 'high'
    medium = 'medium'
    low = 'low'


class UpdateTicketBodyDTO(BaseModel):
    title: Annotated[Optional[str], Field(max_length=200)] = None
    severity: Optional[Severity] = None
    aiSummary: Annotated[Optional[str], Field(max_length=2000)] = None
    aiCategory: Annotated[Optional[str], Field(max_length=200)] = None


class V1JourneyContactDto(BaseModel):
    email: Annotated[Optional[str], Field(examples=['cliente@example.com'])] = None
    phone: Annotated[Optional[str], Field(examples=['56911111111'])] = None
    """
    Phone with country code, digits only
    """


class V1JourneyPendingMomentDto(BaseModel):
    key: str
    name: Optional[str] = None


class Status2(Enum):
    pending = 'pending'
    active = 'active'
    sent = 'sent'
    responded = 'responded'
    done = 'done'
    skipped = 'skipped'


class ToolType(Enum):
    woku = 'woku'
    csat = 'csat'
    ces = 'ces'
    nps = 'nps'
    flow = 'flow'
    form = 'form'


class ToolScope(Enum):
    shared = 'shared'
    per_enrollment = 'per_enrollment'


class ActivationSource(Enum):
    operator = 'operator'
    response = 'response'
    webhook = 'webhook'
    timer = 'timer'
    fallback = 'fallback'


class V1JourneyMomentProgressDto(BaseModel):
    key: str
    name: str
    status: Status2
    toolId: Optional[str] = None
    toolType: Optional[ToolType] = None
    toolScope: Optional[ToolScope] = None
    sentAt: Optional[datetime] = None
    respondedAt: Optional[datetime] = None
    activationSource: Optional[ActivationSource] = None
    hookReceivedAt: Optional[datetime] = None


class Lifecycle(Enum):
    pending = 'pending'
    running = 'running'
    stopping = 'stopping'
    stopped = 'stopped'
    completed = 'completed'


class StartSource(Enum):
    operator = 'operator'
    response = 'response'
    webhook = 'webhook'


class Source(Enum):
    operator = 'operator'
    response = 'response'
    webhook = 'webhook'
    timer = 'timer'
    fallback = 'fallback'


class Next(BaseModel):
    stageKey: str
    name: str
    source: Source
    scheduledFor: Optional[datetime] = None


class V1JourneyParticipationDto(BaseModel):
    id: str
    subjectKey: str
    contact: V1JourneyContactDto
    lifecycle: Lifecycle
    definitionVersion: Optional[float] = None
    startedAt: Optional[datetime] = None
    startSource: Optional[StartSource] = None
    stoppedAt: Optional[datetime] = None
    completedAt: Optional[datetime] = None
    stopRequestedAt: Optional[datetime] = None
    stoppedBy: Optional[str] = None
    stopReason: Optional[str] = None
    dispatchOutcomeUncertain: bool
    createdAt: Optional[datetime] = None
    pendingMoments: list[V1JourneyPendingMomentDto]
    moments: list[V1JourneyMomentProgressDto]
    next: Next


class V1JourneyParticipationPageDto(BaseModel):
    items: list[V1JourneyParticipationDto]
    nextCursor: Optional[str] = None
    """
    Present only when another page exists; omit cursor for the first page.
    """


class StopJourneyParticipationDto(BaseModel):
    reason: Annotated[Optional[str], Field(max_length=280)] = None


class Mode(Enum):
    woku_signature = 'woku_signature'
    url_token = 'url_token'
    sender_hmac = 'sender_hmac'


class V1JourneyConnectionDto(BaseModel):
    stageKey: str
    mode: Mode
    configured: bool
    """
    Credential readiness, not proof of webhook delivery.
    """
    url: str
    """
    Credential-free inbound endpoint. Minting a URL token returns the credential URL separately.
    """


class V1JourneyMomentUrlDto(BaseModel):
    token: str
    """
    Returned only by this operation; store securely.
    """
    url: str
    """
    Credential URL. Minting replaces the prior token, including for existing participations.
    """


class SetSenderSecretDto(BaseModel):
    senderSecret: str
    """
    The signing secret the external system gave you. Stored encrypted; never returned.
    """


class V1PreviewJourneyMomentDto(BaseModel):
    payload: dict[str, Any]
    """
    Sample payload. Does not verify signatures, enroll clients or send invitations.
    """


class V1JourneyTrackerDto(BaseModel):
    name: Annotated[str, Field(examples=['campaign'])]
    value: Annotated[str, Field(examples=['black-friday'])]


class V1JourneyLocaleDto(BaseModel):
    es: Optional[str] = None
    en: Optional[str] = None


class V1JourneyPreviewFolderDto(BaseModel):
    secondaryKey: str
    name: str
    parentSecondaryKey: Optional[str] = None
    parentName: Optional[str] = None


class V1JourneyPreviewContentDto(BaseModel):
    title: str
    imageUrl: Optional[str] = None
    trackers: Optional[list[V1JourneyTrackerDto]] = None
    question: Optional[V1JourneyLocaleDto] = None
    folder: Optional[V1JourneyPreviewFolderDto] = None
    clientFields: dict[str, Union[str, float, bool]]
    """
    Resolved additional client fields.
    """


class V1JourneyPreviewResponseDto(BaseModel):
    matches: bool
    subjectKey: str
    contact: V1JourneyContactDto
    preview: Optional[V1JourneyPreviewContentDto] = None
    """
    Present for matching dynamic webhook content.
    """


class JourneyPlanMemberDto(BaseModel):
    userId: str
    """
    Company member user id.
    """
    role: Role


class JourneyRecipientsDto(BaseModel):
    ticketsEnabled: Optional[bool] = None
    """
    Omit to keep ticket creation enabled.
    """
    plansEnabled: Optional[bool] = None
    """
    Omit to keep plan creation enabled.
    """
    ticketEmails: list[str]
    """
    Ticket email recipients, including the creator by default.
    """
    planMembers: list[JourneyPlanMemberDto]
    """
    Platform users who belong to the journey action-plan group.
    """


class V1JourneyRoutingDto(BaseModel):
    ticketsReady: bool
    plansReady: bool
    ticketDestinationId: Optional[str] = None
    actionPlanGroupId: Optional[str] = None


class V1JourneyToolSpecDto(BaseModel):
    fileId: Optional[str] = None
    """
    Woku uploaded public media ID belonging to this company.
    """
    imageUrl: Optional[str] = None
    """
    Derived media URL. Saving with fileId resolves its authoritative URL.
    """
    descriptionEn: Annotated[Optional[str], Field(max_length=140, min_length=3)] = None
    subject: Optional[V1JourneyLocaleDto] = None
    """
    Variable in the fixed CSAT, CES or NPS question, not the complete question.
    """
    audience: Optional[V1JourneyLocaleDto] = None
    """
    NPS recommendation audience.
    """


class V1JourneySendWindowDto(BaseModel):
    startHour: Annotated[float, Field(ge=0.0, le=23.0)]
    endHour: Annotated[float, Field(ge=1.0, le=24.0)]
    timeZone: Annotated[str, Field(examples=['America/Santiago'])]


class Mode1(Enum):
    """
    Verification configuration only. Set secret material through the credential endpoints.
    """

    woku_signature = 'woku_signature'
    url_token = 'url_token'
    sender_hmac = 'sender_hmac'


class Encoding(Enum):
    hex = 'hex'
    base64 = 'base64'


class SignedPayload(Enum):
    body = 'body'
    timestamp_dot_body = 'timestamp_dot_body'


class V1JourneyVerificationDto(BaseModel):
    mode: Mode1
    """
    Verification configuration only. Set secret material through the credential endpoints.
    """
    header: Optional[str] = None
    encoding: Optional[Encoding] = None
    prefix: Optional[str] = None
    signedPayload: Optional[SignedPayload] = None
    timestampHeader: Optional[str] = None


class V1JourneyPayloadRuleDto(BaseModel):
    path: Annotated[str, Field(examples=['order.status'])]
    equals: Annotated[str, Field(examples=['delivered'])]


class V1JourneyClientFieldDto(BaseModel):
    key: str
    """
    Unique Client.customFields key; at most 20 mappings.
    """
    path: Annotated[str, Field(examples=['customer.tier'])]


class V1JourneyPayloadMapDto(BaseModel):
    subjectKey: Optional[str] = None
    """
    Dotted path to the stable case reference.
    """
    email: Annotated[Optional[str], Field(examples=['customer.email'])] = None
    phone: Annotated[Optional[str], Field(examples=['customer.phone'])] = None
    match: Optional[list[V1JourneyPayloadRuleDto]] = None
    clientFields: Annotated[
        Optional[list[V1JourneyClientFieldDto]], Field(max_length=20)
    ] = None


class Type1(Enum):
    manual = 'manual'
    event = 'event'
    webhook = 'webhook'
    afterStage = 'afterStage'


class Anchor(Enum):
    sent = 'sent'
    response = 'response'
    event = 'event'


class V1JourneyTriggerDto(BaseModel):
    type: Type1
    event: Optional[str] = None
    """
    Legacy event trigger name. Reserved journey events cannot be emitted.
    """
    stage: Optional[str] = None
    """
    afterStage: key of the earlier moment.
    """
    anchor: Optional[Anchor] = None
    delayMs: Annotated[Optional[float], Field(ge=0.0)] = None
    """
    afterStage wait in milliseconds. A v2 zero delay means one hour.
    """
    window: Optional[V1JourneySendWindowDto] = None
    verification: Optional[V1JourneyVerificationDto] = None
    """
    Legacy webhook verification; use webhook.verification in v2.
    """
    payload: Optional[V1JourneyPayloadMapDto] = None
    """
    Legacy webhook mapping; use webhook.payload in v2.
    """


class Mode2(Enum):
    literal = 'literal'
    javascript = 'javascript'


class V1JourneyTextValueDto(BaseModel):
    mode: Mode2
    value: str
    """
    Literal (up to 200 characters) or bounded JavaScript function body (up to 2000). JavaScript receives payload and must return a string; no IO or imports.
    """


class V1JourneyDynamicLocaleDto(BaseModel):
    es: Optional[V1JourneyTextValueDto] = None
    en: Optional[V1JourneyTextValueDto] = None


class V1JourneyTrackerMappingDto(BaseModel):
    name: str
    """
    Tracker name, at most 60 characters. Journey system trackers are reserved.
    """
    path: Annotated[str, Field(examples=['order.id'])]


class V1JourneyWebhookContentDto(BaseModel):
    description: Optional[V1JourneyTextValueDto] = None
    descriptionEn: Optional[V1JourneyTextValueDto] = None
    folderSecondaryKey: Optional[V1JourneyTextValueDto] = None
    folderName: Optional[V1JourneyTextValueDto] = None
    parentFolderSecondaryKey: Optional[V1JourneyTextValueDto] = None
    parentFolderName: Optional[V1JourneyTextValueDto] = None
    subject: Optional[V1JourneyDynamicLocaleDto] = None
    audience: Optional[V1JourneyDynamicLocaleDto] = None
    imageUrlPath: Optional[str] = None
    """
    Woku only: dotted path to a public HTTPS image URL.
    """
    trackers: Annotated[
        Optional[list[V1JourneyTrackerMappingDto]], Field(max_length=20)
    ] = None


class ContentMode(Enum):
    """
    Content source, independent from trigger. Webhook content requires per_enrollment scope.
    """

    manual = 'manual'
    webhook = 'webhook'


class V1JourneyWebhookDto(BaseModel):
    verification: Optional[V1JourneyVerificationDto] = None
    payload: Optional[V1JourneyPayloadMapDto] = None
    contentMode: Optional[ContentMode] = None
    """
    Content source, independent from trigger. Webhook content requires per_enrollment scope.
    """
    schema_: Annotated[Optional[dict[str, Any]], Field(alias='schema')] = None
    """
    Bounded JSON Schema: object root, at most 20000 characters, depth 8, 200 nodes and 50 properties per node. Supports type, properties, required, additionalProperties, items, enum, minLength, maxLength, minimum, maximum, minItems, maxItems, title and description. No references or regex.
    """
    content: Optional[V1JourneyWebhookContentDto] = None


class V1JourneySequenceDto(BaseModel):
    attemptOffsetsMs: list[float]
    """
    Initial invitation and reminder offsets from activation. [0, 86400000] sends one reminder the next day.
    """
    deadlineMs: Annotated[float, Field(ge=1.0)]
    cooldownAfterResponseMs: Annotated[float, Field(ge=0.0)]
    sendWindow: Optional[V1JourneySendWindowDto] = None


class V1JourneyPresentationDto(BaseModel):
    imageUrl: Optional[str] = None
    copy_: Annotated[Optional[V1JourneyLocaleDto], Field(alias='copy')] = None


class Type2(Enum):
    csat = 'csat'
    ces = 'ces'
    woku = 'woku'
    nps = 'nps'
    flow = 'flow'
    form = 'form'


class V1JourneyLegacyToolRefDto(BaseModel):
    type: Type2
    id: str


class Tool(Enum):
    woku = 'woku'
    csat = 'csat'
    ces = 'ces'
    nps = 'nps'


class ToolScope1(Enum):
    """
    V2 defaults to shared within this moment. Dynamic webhook content requires per_enrollment.
    """

    shared = 'shared'
    per_enrollment = 'per_enrollment'


class Channel5(Enum):
    email = 'email'
    whatsapp_first = 'whatsapp_first'


class V1JourneyMomentReadDto(BaseModel):
    key: Annotated[str, Field(pattern='^[A-Za-z0-9_-]{1,64}$')]
    name: Annotated[Optional[str], Field(max_length=80)] = None
    description: Annotated[Optional[str], Field(max_length=280)] = None
    order: Optional[float] = None
    """
    Display order. Execution follows the trigger graph.
    """
    tool: Tool
    toolScope: Optional[ToolScope1] = None
    """
    V2 defaults to shared within this moment. Dynamic webhook content requires per_enrollment.
    """
    toolSpec: Optional[V1JourneyToolSpecDto] = None
    enabled: bool
    trigger: V1JourneyTriggerDto
    webhook: Optional[V1JourneyWebhookDto] = None
    channel: Channel5
    sequence: V1JourneySequenceDto
    presentation: Optional[V1JourneyPresentationDto] = None
    fallbackAfterMs: Annotated[Optional[float], Field(ge=1.0)] = None
    """
    Secondary wait for a webhook-primary moment.
    """
    fallbackFromStage: Optional[str] = None
    """
    Key of the enabled moment that arms the secondary wait.
    """
    toolRef: Optional[V1JourneyLegacyToolRefDto] = None
    """
    Legacy snapshots only. New assignments of existing tools are rejected.
    """


class AuthoringVersion(Enum):
    number_1 = 1
    number_2 = 2


class StartMode(Enum):
    operator = 'operator'
    response = 'response'
    webhook = 'webhook'


class V1JourneyResponseDto(BaseModel):
    id: str
    key: Optional[str] = None
    name: Optional[str] = None
    enabled: bool
    version: float
    authoringVersion: Optional[AuthoringVersion] = None
    startMode: Optional[StartMode] = None
    recipients: Optional[JourneyRecipientsDto] = None
    routing: Optional[V1JourneyRoutingDto] = None
    moments: list[V1JourneyMomentReadDto]
    createdAt: Optional[datetime] = None
    updatedAt: Optional[datetime] = None


class V1JourneyMomentDto(BaseModel):
    key: Annotated[str, Field(pattern='^[A-Za-z0-9_-]{1,64}$')]
    name: Annotated[Optional[str], Field(max_length=80)] = None
    description: Annotated[Optional[str], Field(max_length=280)] = None
    order: Optional[float] = None
    """
    Display order. Execution follows the trigger graph.
    """
    tool: Tool
    toolScope: Optional[ToolScope1] = None
    """
    V2 defaults to shared within this moment. Dynamic webhook content requires per_enrollment.
    """
    toolSpec: Optional[V1JourneyToolSpecDto] = None
    enabled: bool
    trigger: V1JourneyTriggerDto
    webhook: Optional[V1JourneyWebhookDto] = None
    channel: Channel5
    sequence: V1JourneySequenceDto
    presentation: Optional[V1JourneyPresentationDto] = None
    fallbackAfterMs: Annotated[Optional[float], Field(ge=1.0)] = None
    """
    Secondary wait for a webhook-primary moment.
    """
    fallbackFromStage: Optional[str] = None
    """
    Key of the enabled moment that arms the secondary wait.
    """


class AuthoringVersion1(Enum):
    """
    Use 2 for the business-form contract. Existing v1 definitions keep their execution rules.
    """

    number_1 = 1
    number_2 = 2


class StartMode1(Enum):
    """
    Who starts the first moment. Response means a saved first answer, not opening its link.
    """

    operator = 'operator'
    response = 'response'
    webhook = 'webhook'


class V1CreateJourneyBodyDto(BaseModel):
    authHeader: Optional[str] = None
    """
    Legacy body API key. Prefer Authorization: Bearer. Consumed by authentication and never forwarded to journey commands.
    """
    authoringVersion: Optional[AuthoringVersion1] = None
    """
    Use 2 for the business-form contract. Existing v1 definitions keep their execution rules.
    """
    startMode: Optional[StartMode1] = None
    """
    Who starts the first moment. Response means a saved first answer, not opening its link.
    """
    recipients: Optional[JourneyRecipientsDto] = None
    name: Annotated[str, Field(examples=['Viaje de ventas'])]
    enabled: Optional[bool] = False
    """
    A journey is born switched off. Turn it on when it is ready.
    """
    moments: Optional[list[V1JourneyMomentDto]] = None
    """
    The moments of the journey. Each creates a woku, CSAT, CES, or NPS from toolSpec. New v2 moments default to shared within that moment; per_enrollment creates one tool per participation. Existing toolRef assignments are rejected. A zero-day afterStage delay means one hour. In v2 only the first moment can be manual. Later moments use webhook or afterStage; independent webhook settings also let a webhook advance a timed moment. fallbackAfterMs is the optional secondary wait for a webhook-primary moment, anchored to fallbackFromStage. Legacy definitions retain their triggers.
    """


class AuthoringVersion2(Enum):
    number_1 = 1
    number_2 = 2


class StartMode2(Enum):
    operator = 'operator'
    response = 'response'
    webhook = 'webhook'


class V1CreatedJourneyResponseDto(BaseModel):
    id: str
    key: Optional[str] = None
    name: Optional[str] = None
    enabled: bool
    version: float
    authoringVersion: Optional[AuthoringVersion2] = None
    startMode: Optional[StartMode2] = None
    recipients: Optional[JourneyRecipientsDto] = None
    routing: Optional[V1JourneyRoutingDto] = None
    moments: list[V1JourneyMomentReadDto]
    createdAt: Optional[datetime] = None
    updatedAt: Optional[datetime] = None
    webhookSecret: str
    """
    Legacy journey-wide signature secret, returned once. It is not the per-moment URL token or sender secret.
    """


class AuthoringVersion3(Enum):
    """
    Use 2 for the business-form contract. Existing v1 definitions keep their execution rules.
    """

    number_1 = 1
    number_2 = 2


class StartMode3(Enum):
    """
    Who starts the first moment. Response means a saved first answer, not opening its link.
    """

    operator = 'operator'
    response = 'response'
    webhook = 'webhook'


class V1UpdateJourneyBodyDto(BaseModel):
    authHeader: Optional[str] = None
    """
    Legacy body API key. Prefer Authorization: Bearer. Consumed by authentication and never forwarded to journey commands.
    """
    authoringVersion: Optional[AuthoringVersion3] = None
    """
    Use 2 for the business-form contract. Existing v1 definitions keep their execution rules.
    """
    startMode: Optional[StartMode3] = None
    """
    Who starts the first moment. Response means a saved first answer, not opening its link.
    """
    recipients: Optional[JourneyRecipientsDto] = None
    name: Annotated[Optional[str], Field(examples=['Viaje de ventas'])] = None
    enabled: Optional[bool] = None
    moments: Optional[list[V1JourneyMomentDto]] = None


class V1JourneySecretResponseDto(BaseModel):
    webhookSecret: str
    """
    Legacy journey-wide signature secret, returned only by create or rotate. V2 url_token and sender_hmac use separate per-moment credentials.
    """


class V1EnrollSubjectBodyDto(BaseModel):
    authHeader: Optional[str] = None
    """
    Legacy body API key. Prefer Authorization: Bearer. Consumed by authentication and never forwarded to journey commands.
    """
    subjectKey: Annotated[str, Field(examples=['cliente-123'])]
    """
    Your own key for who is enrolled: a customer id, an order, a ticket.
    """
    contact: V1JourneyContactDto
    """
    Where to reach the subject. At least one of email or phone.
    """
    trackers: Optional[list[V1JourneyTrackerDto]] = None
    metadata: Optional[dict[str, Any]] = None
    """
    Anything you want kept with it
    """


class V1JourneyEnrollmentResponseDto(BaseModel):
    subjectKey: str
    journeyId: str


class V1EmitJourneyEventBodyDto(BaseModel):
    authHeader: Optional[str] = None
    """
    Legacy body API key. Prefer Authorization: Bearer. Consumed by authentication and never forwarded to journey commands.
    """
    event: Annotated[str, Field(examples=['crm.deal.won'])]
    subjectKey: Annotated[str, Field(examples=['cliente-123'])]
    contact: Optional[V1JourneyContactDto] = None
    trackers: Optional[list[V1JourneyTrackerDto]] = None
    metadata: Optional[dict[str, Any]] = None


class V1JourneyEventResponseDto(BaseModel):
    journeys: float


class JourneyEntryInfoDto(BaseModel):
    name: Optional[str] = None
    momentName: Optional[str] = None
    tool: Tool
    requiresReference: bool
    """
    A case reference is required when later moments start on webhooks.
    """


class PrepareJourneyEntryDto(BaseModel):
    requestId: UUID
    """
    Stable random request ID for retrying this preparation.
    """
    email: Optional[str] = None
    phone: Annotated[Optional[str], Field(examples=['56912345678'])] = None
    reference: Annotated[Optional[str], Field(max_length=200)] = None


class PreparedJourneyEntryDto(BaseModel):
    companyId: str
    tool: Tool
    toolId: str
    token: str
    """
    Opaque response capability for this prepared first tool. Keep private; preparing alone does not start the journey.
    """
    subjectKey: str
